---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build driver
    type: builder
    artifact_dir: target
    build_type: maven
    script: |-
        #!/bin/bash
        export JAVA_HOME=$JAVA8_HOME
        mvn -B -Pstreams-runner package
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: PIPELINE_API_KEY
    value: ${API_KEY}
    type: text
  - name: PIPELINE_SA_INSTANCE
    value: ${SA_INSTANCE}
    type: text
  - name: PIPELINE_MH_INSTANCE
    value: ${MH_INSTANCE}
    type: text
  - name: PIPELINE_COS_INSTANCE
    value: ${COS_INSTANCE}
    type: text
  jobs:
  - name: Rolling Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      # Push app

      echo $PIPELINE_API_KEY
      echo $PIPELINE_COS_INSTANCE
      echo $PIPELINE_SA_INSTANCE
      echo $PIPELINE_MH_INSTANCE

      echo "generating vcap.json"
            echo "{
              \"streaming-analytics\":[{
                \"name\" : \"streaming-analytics\",
                \"credentials\" : $PIPELINE_SA_INSTANCE
              }],
              \"message_hub\": $PIPELINE_MH_INSTANCE,
              \"cos\": $PIPELINE_COS_INSTANCE
            }" > vcap.json

      java -cp ./example-starter-kit-0.1-SNAPSHOT.jar:./dependency/com.ibm.streams.beam-1.2.1/com.ibm.streams.beam/lib/com.ibm.streams.beam.translation.jar \
            com.ibm.streams.beam.sample.datahistorian.DataHistorian \
            --runner=StreamsRunner \
            --contextType=STREAMING_ANALYTICS_SERVICE \
            --vcapServices=./vcap.json \
            --serviceName=streaming-analytics \
            --beamToolkitDir=./dependency/com.ibm.streams.beam-1.2.1 \
            --jarsToStage=./example-starter-kit-0.1-SNAPSHOT.jar \
            --jobName=$CF_APP_NAME
    docker_image: maven:3.5.3-ibmjava
