version: '2'
template:
  name: Continuous Delivery Toolchain
  description: "This toolchain includes tools to develop and deploy your app. Depending on your app, when you create the toolchain, the GitHub repository will either be empty or will contain source code from your app.\n\nThis toolchain uses tools that are part of the Continuous Delivery service. If an instance of that service isn't already in your organization, when you click **Create**, it is automatically added at no cost to you. For more information and terms, see the [IBM Cloud catalog](/catalog/services/continuous-delivery/).\n\nTo get started, click **Create**."
  required:
    - repo
    - build

toolchain:
  name: {{name}}

services:
  # Github repos
  repo:
    service_id: hostedgit
    parameters:
      repo_url: "{{tag '#zip_url'}}{{tag 'zip_url'}}{{tag '/zip_url'}}{{tag '^zip_url'}}{{tag 'repository'}}{{tag '/zip_url'}}"
      repo_name: "{{tag 'toolchain.name'}}"
      type: {{repoType}}
      has_issues: true
      enable_traceability: true

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: "{{tag 'name'}}"
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          PROD_SPACE_NAME: '{{form.pipeline.parameters.prod-space}}'
          PROD_ORG_NAME: '{{form.pipeline.parameters.prod-organization}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          SA_INSTANCE: '{{form.pipeline.parameters.sa-instance}}'
          MH_INSTANCE: '{{form.pipeline.parameters.mh-instance}}'
          COS_INSTANCE: '{{form.pipeline.parameters.cos-instance}}'
        execute: true

  #Web IDE
  webide:
    service_id: orion

#Deployment
form: {}